# Generated by Django 4.0.5 on 2022-08-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=1, upload_to='project'),
            preserve_default=False,
        ),
    ]
